#FROM python:3.10-slim-buster
FROM ghcr.io/malyuk-a/fl-client-env-builder:latest
LABEL org.opencontainers.image.source https://github.com/oakestra/oakestra

#COPY . /
#RUN pip install -r requirements.txt
# TODO

CMD ["bash", "-c", "echo hi"]
